all:
  hosts:
    kmaster1:
      ansible_host: ""
      ansible_user: ""
      ansible_password: 
      ansible_become_password: ""

    knode1:
      ansible_host: ""
      ansible_user: ""
      ansible_password: 
      ansible_become_password: ""


    knode2:
      ansible_host: ""
      ansible_user: ""
      ansible_password: ""
      ansible_become_password: ""

    knode3:
      ansible_host: ""
      ansible_user: ""
      ansible_password: ""
      ansible_become_password: ""
      
  children:
    kube_control_plane:
      hosts:
        kmaster1:
    kube_node:
      hosts:
        knode1:
        knode2:
        knode3:
    etcd:
      hosts:
        kmaster1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
